export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";

export const GET_COMMENTS_BY_ID_REQUEST = "GET_COMMENTS_BY_ID_REQUEST";
export const GET_COMMENTS_BY_ID_SUCCESS = "GET_COMMENTS_BY_ID_SUCCESS";
export const GET_COMMENTS_BY_ID_FAILURE = "GET_COMMENTS_BY_ID_FAILURE";
