export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const TRAVELER_LOGIN_REQUEST = "TRAVELER_LOGIN_REQUEST";
export const TRAVELER_LOGIN_SUCCESS = "TRAVELER_LOGIN_SUCCESS";
export const TRAVELER_LOGIN_FAILURE = "TRAVELER_LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const TRAVELER_SIGNUP_REQUEST = "TRAVELER_SIGNUP_REQUEST";
export const TRAVELER_SIGNUP_SUCCESS = "TRAVELER_SIGNUP_SUCCESS";
export const TRAVELER_SIGNUP_FAILURE = "TRAVELER_SIGNUP_FAILURE";

export const RESTORE_SESSION = "RESTORE_SESSION";
export const LOGOUT = "LOGOUT";
