export const GET_ALL_PACKAGES_REQUEST = "GET_ALL_PACKAGES_REQUEST";
export const GET_ALL_PACKAGES_SUCCESS = "GET_ALL_PACKAGES_SUCCESS";
export const GET_ALL_PACKAGES_FAILURE = "GET_ALL_PACKAGES_FAILURE";

export const GET_DETAILS_PACKAGES_REQUEST = "GET_DETAILS_PACKAGES_REQUEST";
export const GET_DETAILS_PACKAGES_SUCCESS = "GET_DETAILS_PACKAGES_SUCCESS";
export const GET_DETAILS_PACKAGES_FAILURE = "GET_DETAILS_PACKAGES_FAILURE";
