export const GET_TWEET_BY_ID_REQUEST = "GET_TWEET_BY_ID_REQUEST";
export const GET_TWEET_BY_ID_SUCCESS = "GET_TWEET_BY_ID_SUCCESS";
export const GET_TWEET_BY_ID_FAILURE = "GET_TWEET_BY_ID_FAILURE";

export const GET_ALL_TWEET_REQUEST = "GET_ALL_TWEET_REQUEST";
export const GET_ALL_TWEET_SUCCESS = "GET_ALL_TWEET_SUCCESS";
export const GET_ALL_TWEET_FAILURE = "GET_ALL_TWEET_FAILURE";

export const CREATE_TWEET_REQUEST = "CREATE_TWEET_REQUEST";
export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS";
export const CREATE_TWEET_FAILURE = "CREATE_TWEET_FAILURE";
